In [1]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
import matplotlib

import random
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score


In [2]:
os.chdir('C:\\Users\\Nevena\\Desktop\\LSDM project\\Data\\train')
lifetime=pd.read_csv('lifetime.csv',header=0,index_col=0,na_values='?')
lifetime_features=pd.read_csv('lifetime_features.csv',header=0,index_col=0,na_values='?')
size=pd.read_csv('size.csv',header=0,index_col=0,na_values='?')
spectrum=pd.read_csv('spectrum.csv',header=0,index_col=0,na_values='?')
labels=pd.read_csv('train_labels.csv',header=0,index_col=0,na_values='?')
scattering=pd.read_csv('scattering.csv',header=0,index_col=0,na_values='?')

In [3]:
scattering_np=np.array(scattering)
size_np=np.array(size)
lifetime_np=np.array(lifetime)
lifetime_feat_np=np.array(lifetime_features)
spectrum_np=np.array(spectrum)
#labels_np=np.array(labels)

In [4]:
data = np.concatenate((scattering_np, size_np, lifetime_np, lifetime_feat_np, spectrum_np), axis=1)

In [30]:
data1 = np.concatenate((scattering_np, lifetime_np, spectrum_np), axis=1)

In [31]:
#"Promuckamo" podatke da ne idu redom
indices1 = np.array(range(scattering.shape[0]))

random.seed(0)
random.shuffle(indices1)

new_data = [data[i] for i in indices1]

new_labels = [labels['Pollen'][i] for i in indices1]

new_data1 = [data1[i] for i in indices1]

In [32]:
ind = np.int(np.round(0.8 * len(data)))

train = new_data[:ind]
train_labels = new_labels[:ind]
val = new_data[ind:]
val_labels = new_labels[ind:]

train1 = new_data[:ind]
train_labels1 = new_labels[:ind]

C:\Users\Nevena\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [7]:
from sklearn.svm import SVC
from scipy import stats 

C:\Users\Nevena\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Users\Nevena\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=Tru

In [27]:
classification = SVC(kernel='poly')
classification.fit(train, train_labels)
predict = classification.predict(val)

C:\Users\Nevena\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [28]:
cm = confusion_matrix(val_labels, predict)
f1 = f1_score(val_labels, predict, average="weighted")

print('F1 score: ', f1)
print('Confusion matrix: ')
print(cm)

F1 score:  0.23382753146949994
Confusion matrix: 
[[27 11  8 13  5  6  4 10  1  5  7  4]
 [14 22 12  7  7  4  7  5  4  3 17  6]
 [11  5 16 12  6 13  7  6  3 10  3  2]
 [ 7  3  7 30 12 17  4  1  2  9  7  6]
 [ 8  2  6 13 40  8  6  0  0  1  4  4]
 [ 7  6 16 10 11 18  8  6  2 11  4  4]
 [ 9  3 21 19  8  9 22  0  2  3  7  2]
 [ 7  6 12  3  0  3  0 22 21  6 12  3]
 [ 4  5  9  4  2  2  1 17 34 10 13  1]
 [ 7  2  5 14  4  6  4  4  5 14 11  8]
 [ 2  9  8  6  6 12  3 10 14  7 10  3]
 [ 9 10  7 13  9 12  6  2  5 11 14 23]]


In [29]:
print(classification_report(val_labels, predict))

              precision    recall  f1-score   support

           0       0.24      0.27      0.25       101
           1       0.26      0.20      0.23       108
           2       0.13      0.17      0.14        94
           3       0.21      0.29      0.24       105
           4       0.36      0.43      0.40        92
           5       0.16      0.17      0.17       103
           6       0.31      0.21      0.25       105
           7       0.27      0.23      0.25        95
           8       0.37      0.33      0.35       102
           9       0.16      0.17      0.16        84
          10       0.09      0.11      0.10        90
          11       0.35      0.19      0.25       121

    accuracy                           0.23      1200
   macro avg       0.24      0.23      0.23      1200
weighted avg       0.25      0.23      0.23      1200



In [34]:
classification = SVC(kernel='poly')
classification.fit(train1, train_labels1)
predict1 = classification.predict(val)

C:\Users\Nevena\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [36]:
cm = confusion_matrix(val_labels, predict1)
f1 = f1_score(val_labels, predict1, average="weighted")

print('F1 score: ', f1)
print('Confusion matrix: ')
print(cm)
print(classification_report(val_labels, predict1))

F1 score:  0.23382753146949994
Confusion matrix: 
[[27 11  8 13  5  6  4 10  1  5  7  4]
 [14 22 12  7  7  4  7  5  4  3 17  6]
 [11  5 16 12  6 13  7  6  3 10  3  2]
 [ 7  3  7 30 12 17  4  1  2  9  7  6]
 [ 8  2  6 13 40  8  6  0  0  1  4  4]
 [ 7  6 16 10 11 18  8  6  2 11  4  4]
 [ 9  3 21 19  8  9 22  0  2  3  7  2]
 [ 7  6 12  3  0  3  0 22 21  6 12  3]
 [ 4  5  9  4  2  2  1 17 34 10 13  1]
 [ 7  2  5 14  4  6  4  4  5 14 11  8]
 [ 2  9  8  6  6 12  3 10 14  7 10  3]
 [ 9 10  7 13  9 12  6  2  5 11 14 23]]
              precision    recall  f1-score   support

           0       0.24      0.27      0.25       101
           1       0.26      0.20      0.23       108
           2       0.13      0.17      0.14        94
           3       0.21      0.29      0.24       105
           4       0.36      0.43      0.40        92
           5       0.16      0.17      0.17       103
           6       0.31      0.21      0.25       105
           7       0.27      0.23      0.25     

In [18]:
from sklearn.neighbors import KNeighborsClassifier

C:\Users\Nevena\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:29: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  EPS = np.finfo(np.float).eps


In [21]:
knn = KNeighborsClassifier(n_neighbors=12)
 
knn.fit(train, train_labels)

# Predict on dataset which model has not seen 
predicted_lab=knn.predict(val)
print(knn.predict(val))

C:\Users\Nevena\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:908: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self._y = np.empty(y.shape, dtype=np.int)


[5 6 3 ... 0 6 2]


In [23]:
for i in predicted_lab:
    print(i)

5
6
3
3
3
3
9
9
11
3
7
9
0
7
9
9
8
9
11
3
0
9
3
0
8
5
9
6
3
8
3
5
8
4
9
3
9
3
10
5
4
3
3
9
0
10
4
9
3
3
6
11
8
0
9
10
8
2
9
11
0
9
0
8
3
10
8
0
3
8
8
9
5
5
9
3
3
9
0
3
2
10
8
3
5
6
3
0
3
3
1
7
4
0
2
3
8
4
9
5
9
3
3
8
4
3
5
4
10
4
0
9
8
9
3
0
10
8
10
10
10
9
3
3
2
0
4
10
10
0
3
3
8
9
3
10
4
3
8
3
9
8
9
3
2
3
6
3
5
4
3
10
5
0
4
10
7
3
3
9
0
3
8
9
3
10
8
8
4
4
0
10
0
0
7
9
3
0
3
5
10
7
5
10
3
4
4
3
8
9
8
3
2
3
3
0
9
7
6
3
7
8
5
3
3
8
7
9
2
3
10
3
3
3
10
3
7
3
5
10
11
5
9
5
0
0
7
3
3
9
9
3
3
10
8
10
3
9
3
10
2
9
4
8
0
8
4
8
3
0
3
9
5
10
2
0
3
8
3
3
9
9
5
3
8
8
5
5
8
9
3
2
3
7
9
0
5
9
3
5
7
9
3
7
8
3
3
3
3
3
7
4
9
8
10
3
3
4
0
10
4
9
10
3
4
3
2
8
3
9
4
8
4
4
9
3
8
3
9
8
10
3
9
10
10
4
9
9
10
10
3
6
6
9
5
3
10
3
3
4
4
6
3
3
10
8
5
10
11
9
10
8
3
4
3
3
5
4
8
5
3
8
8
3
3
7
10
10
3
4
3
4
7
8
4
9
6
3
3
8
8
4
1
9
0
4
4
3
4
10
5
3
5
5
7
8
4
3
3
3
3
0
7
7
10
7
2
3
7
4
2
10
9
3
8
5
7
4
2
8
3
9
2
10
0
3
3
9
3
0
9
1
2
4
4
3
8
3
5
0
3
6
8
0
3
6
7
10
4
3
10
10
4
3
3
5
5
4
4
0
0
0
1
9
4
3
6
3
2
3
9
9
5
9

In [22]:
cm = confusion_matrix(val_labels, predicted_lab)
f1 = f1_score(val_labels, predicted_lab, average="weighted")

print('F1 score: ', f1)
print('Confusion matrix: ')
print(cm)

F1 score:  0.27056101743687416
Confusion matrix: 
[[40  3  4 18  8  6  2  4  9  3  4  0]
 [21  5  2 18  6  7  6 13 15  7  8  0]
 [10  1 14 13  5 21  5  2  8 12  2  1]
 [ 7  0  2 52  4 11  0  3  1 21  2  2]
 [ 1  0  1 20 61  3  3  0  1  2  0  0]
 [ 5  1  4 31  2 25  3  1  5 21  3  2]
 [ 2  1 11 37 12 19 15  1  0  2  5  0]
 [ 4  0  0  4  0  0  0 21 20 14 32  0]
 [ 2  1  0 10  1  2  2 10 48  7 19  0]
 [ 1  0  2 26  3  0  1  1  4 35 11  0]
 [ 2  1  3 17  4  6  1  8 11  8 29  0]
 [ 2  1  1 57  3  8  0  0  9 24 10  6]]


In [25]:
from sklearn.metrics import classification_report, confusion_matrix
#print(confusion_matrix(val_labels, predicted_lab))
print(classification_report(val_labels, predicted_lab))

              precision    recall  f1-score   support

           0       0.41      0.40      0.40       101
           1       0.36      0.05      0.08       108
           2       0.32      0.15      0.20        94
           3       0.17      0.50      0.25       105
           4       0.56      0.66      0.61        92
           5       0.23      0.24      0.24       103
           6       0.39      0.14      0.21       105
           7       0.33      0.22      0.26        95
           8       0.37      0.47      0.41       102
           9       0.22      0.42      0.29        84
          10       0.23      0.32      0.27        90
          11       0.55      0.05      0.09       121

    accuracy                           0.29      1200
   macro avg       0.35      0.30      0.28      1200
weighted avg       0.35      0.29      0.27      1200



# Testing on test data

In [39]:
os.chdir('C:\\Users\\Nevena\\Desktop\\LSDM project\\Data\\test')
lifetime_test=pd.read_csv('lifetime.csv',header=0,index_col=0,na_values='?')
lifetime_features_test=pd.read_csv('lifetime_features.csv',header=0,index_col=0,na_values='?')
size_test=pd.read_csv('size.csv',header=0,index_col=0,na_values='?')
spectrum_test=pd.read_csv('spectrum.csv',header=0,index_col=0,na_values='?')
scattering_test=pd.read_csv('scattering.csv',header=0,index_col=0,na_values='?')

In [40]:
scattering_np_test=np.array(scattering_test)
size_np_test=np.array(size_test)
lifetime_np_test=np.array(lifetime_test)
lifetime_feat_np_test=np.array(lifetime_features_test)
spectrum_np_test=np.array(spectrum_test)

In [41]:
test_data = np.concatenate((scattering_np_test, size_np_test, lifetime_np_test, lifetime_feat_np_test, spectrum_np_test), axis=1)

In [42]:
classification_final = SVC(kernel='poly')
classification_final.fit(new_data, new_labels)
predicted_labels_svc=classification_final.predict(test_data)

C:\Users\Nevena\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [44]:
knn.fit(new_data, new_labels)
predicted_labels_knn=knn.predict(test_data)

C:\Users\Nevena\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:908: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self._y = np.empty(y.shape, dtype=np.int)


In [43]:
for i in predicted_labels_svc:
    print(i)

5
3
2
2
6
11
9
5
6
8
6
6
10
7
2
0
10
5
9
0
6
0
5
0
10
4
1
2
1
8
4
0
1
3
11
10
8
5
3
7
9
0
5
4
10
3
4
10
4
3
2
10
0
6
5
3
3
2
11
1
7
11
10
3
6
11
2
1
2
6
3
7
0
10
11
4
10
6
2
1
9
2
11
7
4
9
0
2
2
8
5
3
4
4
1
10
2
3
7
0
4
7
3
2
3
2
10
8
2
2
8
6
3
5
9
2
9
3
10
2
10
8
2
11
3
8
9
0
9
3
11
5
7
5
3
5
3
3
0
7
3
2
0
5
1
6
10
4
11
0
2
5
5
8
7
9
1
10
0
2
1
9
6
0
9
8
7
8
11
4
5
2
0
2
7
0
3
10
4
2
7
3
2
0
7
1
7
9
1
9
2
2
2
0
7
2
2
6
1
3
3
9
8
10
8
9
5
2
1
0
5
5
5
3
8
5
9
9
2
0
8
9
5
10
6
2
0
9
7
4
4
5
4
1
8
0
3
3
5
5
1
5
8
10
0
7
5
5
11
9
6
0
5
7
5
1
7
5
2
4
1
0
2
2
3
8
8
5
10
1
10
10
6
7
7
4
0
10
9
3
0
5
8
3
3
7
1
11
1
3
8
5
9
3
7
10
5
6
10
8
6
10
10
4
7
8
5
10
11
10
7
8
1
7
4
9
2
11
3
0
10
6
1
0
8
11
3
7
4
6
6
7
1
8
11
8
7
3
10
2
3
6
0
3
8
5
2
3
4
2
9
3
7
4
5
1
7
4
3
8
9
9
3
2
8
7
9
0
3
2
10
5
3
0
8
10
8
8
2
9
3
4
2
0
11
3
2
0
10
6
11
2
11
3
6
5
0
10
3
6
2
3
1
7
6
3
3
10
7
2
6
7
7
11
7
7
9
7
2
2
11
11
5
8
3
3
11
2
10
5
1
1
7
3
5
9
4
10
6
2
1
4
6
6
3
7
2
9
8
0
0
4
9
7
0
3
0
1
11
0
0
11
5
9
1
5
8
4

In [45]:
for i in predicted_labels_knn:
    print(i)

9
2
3
5
4
9
9
9
6
8
5
5
9
10
0
3
10
5
10
10
5
11
4
0
3
9
0
3
0
8
4
0
5
3
9
10
8
3
3
7
9
11
6
5
7
9
5
8
5
2
5
7
0
3
7
5
3
9
9
11
9
3
8
11
5
10
3
0
3
2
10
10
5
5
9
3
9
4
9
0
9
10
3
8
4
7
4
0
4
10
3
4
9
5
10
10
5
5
10
6
2
8
2
9
3
3
11
6
8
10
8
3
3
3
2
10
9
10
8
3
8
8
3
11
10
8
9
0
9
8
3
2
8
9
10
9
0
3
11
5
0
2
3
3
10
2
10
9
9
5
5
5
8
10
8
3
10
10
3
5
0
9
5
8
3
0
9
9
3
3
3
9
5
3
8
10
8
10
3
5
8
0
9
0
10
3
10
4
0
3
5
8
9
9
10
3
10
3
0
3
3
3
10
3
9
3
9
3
3
3
9
10
3
2
10
5
9
9
8
2
9
10
3
9
3
10
2
10
7
3
3
3
3
0
10
1
3
3
10
10
0
2
8
7
0
3
3
3
9
9
9
5
5
10
10
7
7
3
9
5
0
3
10
3
5
9
10
2
9
7
8
10
3
10
7
9
3
7
9
3
0
3
8
5
9
7
5
3
5
3
8
5
10
4
10
7
3
3
8
8
3
5
9
4
10
7
9
5
10
9
10
10
8
9
3
9
2
5
3
0
3
0
9
11
8
3
3
9
1
4
3
10
10
2
9
2
9
10
8
3
10
3
6
9
7
5
9
5
9
9
3
3
9
6
9
0
10
4
8
3
10
10
5
9
3
10
3
0
5
5
5
3
3
11
3
10
3
8
5
10
3
3
3
2
3
3
10
9
0
3
10
9
11
1
9
3
0
3
3
9
9
0
8
10
5
9
3
10
7
8
5
9
9
3
9
10
0
7
7
7
9
9
8
3
10
3
3
2
8
3
5
0
8
3
3
9
2
3
5
9
5
3
3
11
3
7
5
5
9
0
3
5
3
8
0
5
9
8
3
3
0
8

In [46]:
len(predicted_labels_knn)

3866

In [49]:
ista_pred=0
for i in range(len(predicted_labels_knn)):
    if (predicted_labels_knn[i]==predicted_labels_svc[i]):
        ista_pred=ista_pred+1
print(ista_pred)        

942


In [51]:
df = pd.DataFrame(predicted_labels_svc, columns=['Pollen'])

df.to_csv('predicted_labels_svc.csv')

In [61]:
datat=pd.read_csv('predicted_labels_svc.csv')

datat.rename(columns = {'Unnamed: 0':'ID'}, inplace = True)

In [63]:
datat.to_csv('predicted_labels_svc.csv', index=False)

In [66]:
dfk = pd.DataFrame(predicted_labels_knn, columns=['Pollen'])
dfk.to_csv('predicted_labels_knn.csv')

In [67]:
datak=pd.read_csv('predicted_labels_knn.csv')
datak.rename(columns = {'Unnamed: 0':'ID'}, inplace = True)

In [68]:
datak.to_csv('predicted_labels_knn.csv', index=False)

# Rnd forest

In [ ]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels);